#!/usr/bin/bash

DOCKER_BUILDKIT=1 docker build -t tomcat0x42/vaultlinux .

# extract the binaries from the container
docker create --name extract tomcat0x42/ciphervault
docker cp extract:/vaultlinux.iso ./
docker rm extract
